export const CONSTANTS = {
  ENV: {
    DEV: 'DEV',
    STAGING: 'STAGING',
    PROD: 'PROD',
  },
  DATA_SOURCE: 'DATA_SOURCE',
  DB_REPOSITORIES: {
    VEICULO_REPOSITORY: 'VEICULOS_REPOSITORY',
    EMPRESA_REPOSITORY: 'EMPRESA_REPOSITORY',
    ESTACIONAMENTO_REPOSITORY: 'ESTACIONAMENTO_REPOSITORY',
  },
};
